#!/bin/sh
gnome-terminal -- bash -c "python3 player.py player-1.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-2.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-3.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-4.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-5.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-6.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-7.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-8.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-9.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-10.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-11.txt; exec bash"
gnome-terminal -- bash -c "python3 player.py player-12.txt; exec bash"
